### ISSUE TITLE
AndroidAPK not working

### ISSUE THREAD

**Issue by FlorianKirmaier** [gluonhq/hello-gluon-ci#3]
Hi Gluon,
I tried to apply the CI-Logic to a project but noticed that the android-app wasn't starting.
After further investigation I've noticed that the Hello-gluon-ci android apk isn't working.

I've downloaded it from this page: https://github.com/gluonhq/hello-gluon-ci/actions/runs/548055765
I've installed it on a Zenfone6 and on a Samsung S10e, and on both devices the application didn't start.

This is the output:
```
02-24 13:20:25.278 26084 26084 V GraalActivity: surfaceCreated for com.gluonhq.helloandroid.MainActivity@226089b
02-24 13:20:25.278 26084 26084 V GraalActivity: loading substrate library
02-24 13:20:25.380 26084 26084 D AndroidRuntime: Shutting down VM
02-24 13:20:25.381 26084 26084 E AndroidRuntime: FATAL EXCEPTION: main
02-24 13:20:25.381 26084 26084 E AndroidRuntime: Process: com.gluonhq.samples.hellogluon, PID: 26084
02-24 13:20:25.381 26084 26084 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZdaPv" referenced by "/data/app/~~h8R9ow3hhK5u7p5jESJZRg==/com.gluonhq.samples.hellogluon-GZ2Saw06TQZD1v-CzYLKGw==/lib/arm64/libsubstrate.so"...
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1664)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.view.SurfaceView.updateSurface(SurfaceView.java:1173)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.view.SurfaceView.lambda$new$0$SurfaceView(SurfaceView.java:173)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.view.-$$Lambda$SurfaceView$w68OV7dB_zKVNsA-r0IrAUtyWas.onPreDraw(Unknown Source:2)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3115)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1966)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8226)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:878)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:811)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:248)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7787)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-24 13:20:25.381 26084 26084 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
02-24 13:20:25.383  1600 26106 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
02-24 13:20:25.383  1600  9392 W ActivityTaskManager:   Force finishing activity com.gluonhq.samples.hellogluon/com.gluonhq.helloandroid.MainActivity
```

**Comment by jperedadnr** [comment]
Fixed with #4
