### ISSUE TITLE
vmone-windows-x64.zip. Unexpected status code: 404

### ISSUE THREAD

**Issue by ctoabidmaqbool** [gluonhq/hello-gluon-ci#37]
I am facing issue, with new GraalVM release e.g. 23.x and Gluon-Maven-Plugin-Snapshot!

https://github.com/gluonhq/vmone/issues/5

```
D:\GraalVM-Projects\gluonhq\hello-gluon-ci>mvnw -Pdesktop gluonfx:build gluonfx:package
[0.321s][warning][jit,compilation] JVMCI compiler disabled after 11 of 11 upcalls had errors (Last error: "uncaught exception in call_HotSpotJVMCIRuntime_compileMethod [jdk.vm.ci.common.JVMCIError: VM config values missing that should be present in JDK 23 jvmci-23+25-jvmci-b01 windows-amd64 (java.home=D:\Programs\graalvm-java23-windows-amd64-gluon-23+25.1-dev, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=23+25-jvmci-b01):
    HeapRegion::LogOfHRGrainBytes at jdk.graal.compiler/jdk.graal.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:400)
Set the debug.jdk.graal.jvmciConfigCheck system property to "ignore" to suppress this error or to "warn" to emit a warning and continue execution.
Currently used Java home directory is D:\Programs\graalvm-java23-windows-amd64-gluon-23+25.1-dev.
Currently used VM configuration is: OpenJDK 64-Bit Server VM
]"). Use -Xlog:jit+compilation for more detail.
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.gluonhq.samples:hellogluon >-------------------
[INFO] Building HelloGluon 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- gluonfx-maven-plugin:1.0.24-SNAPSHOT:build (default-cli) @ hellogluon ---
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[0.293s][warning][jit,compilation] JVMCI compiler disabled after 11 of 11 upcalls had errors (Last error: "uncaught exception in call_HotSpotJVMCIRuntime_compileMethod [jdk.vm.ci.common.JVMCIError: VM config values missing that should be present in JDK 23 jvmci-23+25-jvmci-b01 windows-amd64 (java.home=D:\Programs\graalvm-java23-windows-amd64-gluon-23+25.1-dev, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=23+25-jvmci-b01):
    HeapRegion::LogOfHRGrainBytes at jdk.graal.compiler/jdk.graal.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:400)
Set the debug.jdk.graal.jvmciConfigCheck system property to "ignore" to suppress this error or to "warn" to emit a warning and continue execution.
Currently used Java home directory is D:\Programs\graalvm-java23-windows-amd64-gluon-23+25.1-dev.
Currently used VM configuration is: OpenJDK 64-Bit Server VM
]"). Use -Xlog:jit+compilation for more detail.
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.gluonhq.samples:hellogluon >-------------------
[INFO] Building HelloGluon 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> gluonfx-maven-plugin:1.0.24-SNAPSHOT:compile (default-cli) > process-classes @ hellogluon >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellogluon ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hellogluon ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< gluonfx-maven-plugin:1.0.24-SNAPSHOT:compile (default-cli) < process-classes @ hellogluon <<<
[INFO]
[INFO]
[INFO] --- gluonfx-maven-plugin:1.0.24-SNAPSHOT:compile (default-cli) @ hellogluon ---
Configuration: ProjectConfiguration{graalPath='D:\Programs\graalvm-java23-windows-amd64-gluon-23+25.1-dev', javaStaticSdkVersion='24-1', javafxStaticSdkVersion='24-ea+7.1', javaVersion=23, graalVersion=23, useJNI=true, useJavaFX=true, usePrismSW=false, enableCheckHash=true, targetTriplet=x86_64-microsoft-windows, hostTriplet=x86_64-microsoft-windows, backend='null', bundlesList=[], resourcesList=[], reflectionList=[], jniList=[], initBuildTimeList=[], runtimeArgsList=[], releaseSymbolsList=null, appName='HelloGluon', releaseConfiguration='ReleaseConfiguration{packageType=null, description='The HelloGluon app', vendor='Gluon', version='null', macAppStore=false, macSigningUserName=null, macAppCategory=null, bundleName='null', bundleVersion='null', bundleShortVersion='null', providedSigningIdentity='null', providedProvisioningProfile='null', skipSigning=false, simulatorDevice='null', appLabel='null', versionCode='null', versionName='null', providedKeyStorePath='null', providedKeyStorePassword='null', providedKeyAlias='null', providedKeyAliasPassword='null'}', mainClassName='com.gluonhq.hello.HelloGluonApp', classpath='D:\GraalVM-Projects\gluonhq\hello-gluon-ci\target\classes;D:\.my-m2\repository\com\gluonhq\charm-glisten\6.2.3\charm-glisten-6.2.3.jar;C:\Users\MSC-30\.m2\repository\com\gluonhq\attach\display\4.0.21\display-4.0.21-desktop.jar;D:\.my-m2\repository\com\gluonhq\attach\display\4.0.21\display-4.0.21.jar;C:\Users\MSC-30\.m2\repository\com\gluonhq\attach\lifecycle\4.0.21\lifecycle-4.0.21-desktop.jar;D:\.my-m2\repository\com\gluonhq\attach\lifecycle\4.0.21\lifecycle-4.0.21.jar;C:\Users\MSC-30\.m2\repository\com\gluonhq\attach\statusbar\4.0.21\statusbar-4.0.21.jar;D:\.my-m2\repository\com\gluonhq\attach\statusbar\4.0.21\statusbar-4.0.21.jar;C:\Users\MSC-30\.m2\repository\com\gluonhq\attach\storage\4.0.21\storage-4.0.21-desktop.jar;D:\.my-m2\repository\com\gluonhq\attach\storage\4.0.21\storage-4.0.21.jar;D:\.my-m2\repository\com\gluonhq\attach\util\4.0.21\util-4.0.21.jar;D:\.my-m2\repository\org\openjfx\javafx-base\24-ea+5\javafx-base-24-ea+5-win.jar;D:\.my-m2\repository\org\openjfx\javafx-base\24-ea+5\javafx-base-24-ea+5.jar;D:\.my-m2\repository\org\openjfx\javafx-controls\24-ea+5\javafx-controls-24-ea+5-win.jar;D:\.my-m2\repository\org\openjfx\javafx-controls\24-ea+5\javafx-controls-24-ea+5.jar;D:\.my-m2\repository\org\openjfx\javafx-graphics\24-ea+5\javafx-graphics-24-ea+5-win.jar;D:\.my-m2\repository\org\openjfx\javafx-graphics\24-ea+5\javafx-graphics-24-ea+5.jar'}
[Sun Sep 08 07:14:16 PKT 2024][INFO] ==================== COMPILE TASK ====================
             _______  ___      __   __  _______  __    _
            |       ||   |    |  | |  ||       ||  |  | |
            |    ___||   |    |  | |  ||   _   ||   |_| |
            |   | __ |   |    |  |_|  ||  | |  ||       |
            |   ||  ||   |___ |       ||  |_|  ||  _    |
            |   |_| ||       ||       ||       || | |   |
            |_______||_______||_______||_______||_|  |__|

    Access to the latest docs, tips and tricks and more info on
    how to get support? Register your usage of Gluon Substrate now at

    https://gluonhq.com/activate



[Sun Sep 08 07:14:18 PKT 2024][INFO] We will now compile your code for x86_64-microsoft-windows. This may take some time.
[Sun Sep 08 07:14:18 PKT 2024][FINE] Processing JavaStatic dependencies at C:\Users\MSC-30\.gluon\substrate\javaStaticSdk\24-1\windows-x86_64\lib
[Sun Sep 08 07:14:18 PKT 2024][FINE] Processing JavaFXStatic dependencies at C:\Users\MSC-30\.gluon\substrate\javafxStaticSdk\24-ea+7.1\windows-x86_64\sdk\lib
[Sun Sep 08 07:14:18 PKT 2024][INFO] Downloading Java Static Libs...
[Sun Sep 08 07:14:18 PKT 2024][FINE] Processing zip file: url = https://github.com/gluonhq/vmone/releases/download/gvm-24-1/vmone-windows-x64.zip, zip = C:\Users\MSC-30\.gluon\substrate\gvm-24-1\vmone-windows-x64.zip, subDir = javaStaticSdk, levels = [24-1, windows-x86_64], md5 = javaStaticSdk-windows-x86_64.md5
[Sun Sep 08 07:14:18 PKT 2024][FINE] download from link: https://github.com/gluonhq/vmone/releases/download/gvm-24-1/vmone-windows-x64.zip
[Sun Sep 08 07:14:19 PKT 2024][SEVERE] download from link failed with status: 404, and body: null
Check the log files under D:\GraalVM-Projects\gluonhq\hello-gluon-ci\target\gluonfx\x86_64-windows\gvm\log
And please check https://docs.gluonhq.com/ for more information.
java.lang.RuntimeException: Error downloading zips: java.io.IOException: Error downloading link from https://github.com/gluonhq/vmone/releases/download/gvm-24-1/vmone-windows-x64.zip. Unexpected status code: 404
        at com.gluonhq.substrate.util.FileDeps.setupDependencies(FileDeps.java:334)
        at com.gluonhq.substrate.util.FileDeps.resolvePath(FileDeps.java:174)
        at com.gluonhq.substrate.util.FileDeps.getJavaFXSDKLibsPath(FileDeps.java:106)
        at com.gluonhq.substrate.target.AbstractTargetConfiguration.processClassPath(AbstractTargetConfiguration.java:788)
        at com.gluonhq.substrate.target.AbstractTargetConfiguration.validateCompileRequirements(AbstractTargetConfiguration.java:392)
        at com.gluonhq.substrate.target.AbstractTargetConfiguration.compile(AbstractTargetConfiguration.java:132)
[INFO] ------------------------------------------------------------------------
        at com.gluonhq.substrate.SubstrateDispatcher.nativeCompile(SubstrateDispatcher.java:422)
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
        at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:54)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:299)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[INFO] Total time:  4.472 s
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:963)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:296)
[INFO] Finished at: 2024-09-08T07:14:19+05:00
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[INFO] ------------------------------------------------------------------------
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.24-SNAPSHOT:compile (default-cli) on project hellogluon: Error: Error downloading zips: java.io.IOException: Error downloading link from https://github.com/gluonhq/vmone/releases/download/gvm-24-1/vmone-windows-x64.zip. Unexpected status code: 404 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Skipping HelloGluon
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.795 s
[INFO] Finished at: 2024-09-08T07:14:19+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.24-SNAPSHOT:build (default-cli) on project hellogluon: Error, gluonfx:build failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by ShiYioo** [comment]
I'm also having a similar issue that doesn't seem to be resolved at the moment

**Comment by ShiYioo** [comment]
It seems that the current version of 1.0.24 does not support Windows

**Comment by ctoabidmaqbool** [comment]
@2743305544 Yeah! Windows support is not yet availabe in v1.0.24.
When it will be supported it's not mentioned by actual devs!
